### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by BaiYunpeng1949** [chenxy99/Scanpaths#1]
Hi, we want to test some dataset on your brilliant model, may I ask do you provide any pretrained models? I did not find them in the github.

**Comment by chenxy99** [comment]
Hello Yunpeng,

For the specific datasets (such as OSIE, AiR, COCO_Search18), you can go to the corresponding directory. Then you will find the link of the pretrained model is in `Evaluate on test split'.
